// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: transport/internet/dnstt/config.proto

package dnstt

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TunnelPublicKey string                 `protobuf:"bytes,1,opt,name=tunnel_public_key,json=tunnelPublicKey,proto3" json:"tunnel_public_key,omitempty"`
	TunnelAddress   string                 `protobuf:"bytes,2,opt,name=tunnel_address,json=tunnelAddress,proto3" json:"tunnel_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_transport_internet_dnstt_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_dnstt_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_transport_internet_dnstt_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetTunnelPublicKey() string {
	if x != nil {
		return x.TunnelPublicKey
	}
	return ""
}

func (x *Config) GetTunnelAddress() string {
	if x != nil {
		return x.TunnelAddress
	}
	return ""
}

var File_transport_internet_dnstt_config_proto protoreflect.FileDescriptor

const file_transport_internet_dnstt_config_proto_rawDesc = "" +
	"\n" +
	"%transport/internet/dnstt/config.proto\x12\x1dxray.transport.internet.dnstt\"[\n" +
	"\x06Config\x12*\n" +
	"\x11tunnel_public_key\x18\x01 \x01(\tR\x0ftunnelPublicKey\x12%\n" +
	"\x0etunnel_address\x18\x02 \x01(\tR\rtunnelAddressB\x80\x01\n" +
	"!com.xray.transport.internet.dnsttP\x01Z9github.com/GFW-knocker/Xray-core/transport/internet/dnstt\xaa\x02\x1dXray.Transport.Internet.Dnsttb\x06proto3"

var (
	file_transport_internet_dnstt_config_proto_rawDescOnce sync.Once
	file_transport_internet_dnstt_config_proto_rawDescData []byte
)

func file_transport_internet_dnstt_config_proto_rawDescGZIP() []byte {
	file_transport_internet_dnstt_config_proto_rawDescOnce.Do(func() {
		file_transport_internet_dnstt_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_internet_dnstt_config_proto_rawDesc), len(file_transport_internet_dnstt_config_proto_rawDesc)))
	})
	return file_transport_internet_dnstt_config_proto_rawDescData
}

var (
	file_transport_internet_dnstt_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
	file_transport_internet_dnstt_config_proto_goTypes  = []any{
		(*Config)(nil), // 0: xray.transport.internet.dnstt.Config
	}
)
var file_transport_internet_dnstt_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_internet_dnstt_config_proto_init() }
func file_transport_internet_dnstt_config_proto_init() {
	if File_transport_internet_dnstt_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_internet_dnstt_config_proto_rawDesc), len(file_transport_internet_dnstt_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_internet_dnstt_config_proto_goTypes,
		DependencyIndexes: file_transport_internet_dnstt_config_proto_depIdxs,
		MessageInfos:      file_transport_internet_dnstt_config_proto_msgTypes,
	}.Build()
	File_transport_internet_dnstt_config_proto = out.File
	file_transport_internet_dnstt_config_proto_goTypes = nil
	file_transport_internet_dnstt_config_proto_depIdxs = nil
}
