// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: transport/internet/vaydns/config.proto

package vaydns

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerPublicKey string                 `protobuf:"bytes,1,opt,name=server_public_key,json=serverPublicKey,proto3" json:"server_public_key,omitempty"`
	ServerAddress   string                 `protobuf:"bytes,2,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	ResolverType    string                 `protobuf:"bytes,3,opt,name=resolver_type,json=resolverType,proto3" json:"resolver_type,omitempty"`
	DnsttCompat     bool                   `protobuf:"varint,4,opt,name=dnstt_compat,json=dnsttCompat,proto3" json:"dnstt_compat,omitempty"`
	ClientidSize    int32                  `protobuf:"varint,5,opt,name=clientid_size,json=clientidSize,proto3" json:"clientid_size,omitempty"`
	MaxQnameLen     int32                  `protobuf:"varint,6,opt,name=max_qname_len,json=maxQnameLen,proto3" json:"max_qname_len,omitempty"`
	MaxNumLabels    int32                  `protobuf:"varint,7,opt,name=max_num_labels,json=maxNumLabels,proto3" json:"max_num_labels,omitempty"`
	Rps             float64                `protobuf:"fixed64,8,opt,name=rps,proto3" json:"rps,omitempty"`
	IdleTimeout     string                 `protobuf:"bytes,9,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	Keepalive       string                 `protobuf:"bytes,10,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	MaxStreams      int32                  `protobuf:"varint,11,opt,name=max_streams,json=maxStreams,proto3" json:"max_streams,omitempty"`
	UdpWorkers      int32                  `protobuf:"varint,12,opt,name=udp_workers,json=udpWorkers,proto3" json:"udp_workers,omitempty"`
	UdpTimeout      string                 `protobuf:"bytes,13,opt,name=udp_timeout,json=udpTimeout,proto3" json:"udp_timeout,omitempty"`
	UdpSharedSocket bool                   `protobuf:"varint,14,opt,name=udp_shared_socket,json=udpSharedSocket,proto3" json:"udp_shared_socket,omitempty"`
	UdpAcceptErrors bool                   `protobuf:"varint,15,opt,name=udp_accept_errors,json=udpAcceptErrors,proto3" json:"udp_accept_errors,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_transport_internet_vaydns_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_vaydns_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_transport_internet_vaydns_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetServerPublicKey() string {
	if x != nil {
		return x.ServerPublicKey
	}
	return ""
}

func (x *Config) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *Config) GetResolverType() string {
	if x != nil {
		return x.ResolverType
	}
	return ""
}

func (x *Config) GetDnsttCompat() bool {
	if x != nil {
		return x.DnsttCompat
	}
	return false
}

func (x *Config) GetClientidSize() int32 {
	if x != nil {
		return x.ClientidSize
	}
	return 0
}

func (x *Config) GetMaxQnameLen() int32 {
	if x != nil {
		return x.MaxQnameLen
	}
	return 0
}

func (x *Config) GetMaxNumLabels() int32 {
	if x != nil {
		return x.MaxNumLabels
	}
	return 0
}

func (x *Config) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *Config) GetIdleTimeout() string {
	if x != nil {
		return x.IdleTimeout
	}
	return ""
}

func (x *Config) GetKeepalive() string {
	if x != nil {
		return x.Keepalive
	}
	return ""
}

func (x *Config) GetMaxStreams() int32 {
	if x != nil {
		return x.MaxStreams
	}
	return 0
}

func (x *Config) GetUdpWorkers() int32 {
	if x != nil {
		return x.UdpWorkers
	}
	return 0
}

func (x *Config) GetUdpTimeout() string {
	if x != nil {
		return x.UdpTimeout
	}
	return ""
}

func (x *Config) GetUdpSharedSocket() bool {
	if x != nil {
		return x.UdpSharedSocket
	}
	return false
}

func (x *Config) GetUdpAcceptErrors() bool {
	if x != nil {
		return x.UdpAcceptErrors
	}
	return false
}

var File_transport_internet_vaydns_config_proto protoreflect.FileDescriptor

const file_transport_internet_vaydns_config_proto_rawDesc = "" +
	"\n" +
	"&transport/internet/vaydns/config.proto\x12\x1exray.transport.internet.vaydns\"\xa0\x04\n" +
	"\x06Config\x12*\n" +
	"\x11server_public_key\x18\x01 \x01(\tR\x0fserverPublicKey\x12%\n" +
	"\x0eserver_address\x18\x02 \x01(\tR\rserverAddress\x12#\n" +
	"\rresolver_type\x18\x03 \x01(\tR\fresolverType\x12!\n" +
	"\fdnstt_compat\x18\x04 \x01(\bR\vdnsttCompat\x12#\n" +
	"\rclientid_size\x18\x05 \x01(\x05R\fclientidSize\x12\"\n" +
	"\rmax_qname_len\x18\x06 \x01(\x05R\vmaxQnameLen\x12$\n" +
	"\x0emax_num_labels\x18\a \x01(\x05R\fmaxNumLabels\x12\x10\n" +
	"\x03rps\x18\b \x01(\x01R\x03rps\x12!\n" +
	"\fidle_timeout\x18\t \x01(\tR\vidleTimeout\x12\x1c\n" +
	"\tkeepalive\x18\n" +
	" \x01(\tR\tkeepalive\x12\x1f\n" +
	"\vmax_streams\x18\v \x01(\x05R\n" +
	"maxStreams\x12\x1f\n" +
	"\vudp_workers\x18\f \x01(\x05R\n" +
	"udpWorkers\x12\x1f\n" +
	"\vudp_timeout\x18\r \x01(\tR\n" +
	"udpTimeout\x12*\n" +
	"\x11udp_shared_socket\x18\x0e \x01(\bR\x0fudpSharedSocket\x12*\n" +
	"\x11udp_accept_errors\x18\x0f \x01(\bR\x0fudpAcceptErrorsB\x83\x01\n" +
	"\"com.xray.transport.internet.vaydnsP\x01Z:github.com/GFW-knocker/Xray-core/transport/internet/vaydns\xaa\x02\x1eXray.Transport.Internet.Vaydnsb\x06proto3"

var (
	file_transport_internet_vaydns_config_proto_rawDescOnce sync.Once
	file_transport_internet_vaydns_config_proto_rawDescData []byte
)

func file_transport_internet_vaydns_config_proto_rawDescGZIP() []byte {
	file_transport_internet_vaydns_config_proto_rawDescOnce.Do(func() {
		file_transport_internet_vaydns_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_internet_vaydns_config_proto_rawDesc), len(file_transport_internet_vaydns_config_proto_rawDesc)))
	})
	return file_transport_internet_vaydns_config_proto_rawDescData
}

var file_transport_internet_vaydns_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transport_internet_vaydns_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.transport.internet.vaydns.Config
}
var file_transport_internet_vaydns_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_internet_vaydns_config_proto_init() }
func file_transport_internet_vaydns_config_proto_init() {
	if File_transport_internet_vaydns_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_internet_vaydns_config_proto_rawDesc), len(file_transport_internet_vaydns_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_internet_vaydns_config_proto_goTypes,
		DependencyIndexes: file_transport_internet_vaydns_config_proto_depIdxs,
		MessageInfos:      file_transport_internet_vaydns_config_proto_msgTypes,
	}.Build()
	File_transport_internet_vaydns_config_proto = out.File
	file_transport_internet_vaydns_config_proto_goTypes = nil
	file_transport_internet_vaydns_config_proto_depIdxs = nil
}
