// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.2
// source: proxy/masque/config.proto

package masque

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config_DomainStrategy int32

const (
	Config_FORCE_IP   Config_DomainStrategy = 0
	Config_FORCE_IP4  Config_DomainStrategy = 1
	Config_FORCE_IP6  Config_DomainStrategy = 2
	Config_FORCE_IP46 Config_DomainStrategy = 3
	Config_FORCE_IP64 Config_DomainStrategy = 4
)

// Enum value maps for Config_DomainStrategy.
var (
	Config_DomainStrategy_name = map[int32]string{
		0: "FORCE_IP",
		1: "FORCE_IP4",
		2: "FORCE_IP6",
		3: "FORCE_IP46",
		4: "FORCE_IP64",
	}
	Config_DomainStrategy_value = map[string]int32{
		"FORCE_IP":   0,
		"FORCE_IP4":  1,
		"FORCE_IP6":  2,
		"FORCE_IP46": 3,
		"FORCE_IP64": 4,
	}
)

func (x Config_DomainStrategy) Enum() *Config_DomainStrategy {
	p := new(Config_DomainStrategy)
	*p = x
	return p
}

func (x Config_DomainStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_DomainStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_masque_config_proto_enumTypes[0].Descriptor()
}

func (Config_DomainStrategy) Type() protoreflect.EnumType {
	return &file_proxy_masque_config_proto_enumTypes[0]
}

func (x Config_DomainStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_DomainStrategy.Descriptor instead.
func (Config_DomainStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proxy_masque_config_proto_rawDescGZIP(), []int{0, 0}
}

type Config_Transport int32

const (
	// Extended CONNECT over HTTP/3, packets in QUIC datagrams. The default.
	Config_H3 Config_Transport = 0
	// Extended CONNECT over HTTP/2, packets as DATAGRAM capsules on the request
	// stream. For paths where UDP is unusable; TCP underneath means head-of-line
	// blocking.
	Config_H2 Config_Transport = 1
)

// Enum value maps for Config_Transport.
var (
	Config_Transport_name = map[int32]string{
		0: "H3",
		1: "H2",
	}
	Config_Transport_value = map[string]int32{
		"H3": 0,
		"H2": 1,
	}
)

func (x Config_Transport) Enum() *Config_Transport {
	p := new(Config_Transport)
	*p = x
	return p
}

func (x Config_Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_masque_config_proto_enumTypes[1].Descriptor()
}

func (Config_Transport) Type() protoreflect.EnumType {
	return &file_proxy_masque_config_proto_enumTypes[1]
}

func (x Config_Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_Transport.Descriptor instead.
func (Config_Transport) EnumDescriptor() ([]byte, []int) {
	return file_proxy_masque_config_proto_rawDescGZIP(), []int{0, 1}
}

// Config is an outbound that carries traffic over MASQUE, an IP tunnel built on
// HTTP extended CONNECT (RFC 9220) with the packets themselves in HTTP
// datagrams (RFC 9297) or DATAGRAM capsules (RFC 9484).
//
// Only what MASQUE itself needs lives here. The TLS of the connection
// underneath, which is server name, ECH, certificate pinning and fingerprint,
// comes from streamSettings the way it does for every other outbound, and the
// socket options, dialerProxy chaining and udpmasks come from there too.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The edge to reach, as "host:port".
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// The addresses the tunnel holds locally, in CIDR or bare form. When empty the
	// address the edge assigns over the tunnel is used instead.
	Address []string `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	// PKCS#8 PEM of the P-256 private key enrolled with the edge. The edge
	// authorises by the public key registered against the account, so there is no
	// certificate authority anywhere in this.
	PrivateKey string `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// PEM of the self-signed certificate carrying that key. Regenerated from
	// private_key when empty, which is the normal case.
	Certificate string           `protobuf:"bytes,4,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Transport   Config_Transport `protobuf:"varint,5,opt,name=transport,proto3,enum=xray.proxy.masque.Config_Transport" json:"transport,omitempty"`
	// The :authority and :path of the CONNECT request.
	Authority string `protobuf:"bytes,6,opt,name=authority,proto3" json:"authority,omitempty"`
	Path      string `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	// The :protocol of the extended CONNECT. Cloudflare's edge wants
	// "cf-connect-ip" rather than RFC 9484's "connect-ip".
	ConnectProtocol string `protobuf:"bytes,8,opt,name=connect_protocol,json=connectProtocol,proto3" json:"connect_protocol,omitempty"`
	Mtu             int32  `protobuf:"varint,9,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Resolvers to use through the tunnel, matching the WireGuard outbound's
	// remoteDNS.
	DNS            []string              `protobuf:"bytes,10,rep,name=DNS,proto3" json:"DNS,omitempty"`
	DomainStrategy Config_DomainStrategy `protobuf:"varint,11,opt,name=domain_strategy,json=domainStrategy,proto3,enum=xray.proxy.masque.Config_DomainStrategy" json:"domain_strategy,omitempty"`
	// Hex SHA-256 of the SubjectPublicKeyInfo of the edge certificates to accept.
	//
	// The edge cannot be verified the ordinary way: it serves a different
	// certificate per SNI and some of them are self-signed, so a chain check
	// fails on a connection that is perfectly good. Skipping verification instead
	// would leave the tunnel open to anyone on the path, so the leaf's public key
	// is pinned and the chain is what gets skipped.
	//
	// Left empty, the known Cloudflare keys are used. Note this pins the public
	// key, not the certificate, so it survives the edge renewing a certificate for
	// the same key; streamSettings' own pinnedPeerCertSha256 hashes the whole
	// certificate and does not.
	PinnedPeerPublicKeySha256 []string `protobuf:"bytes,12,rep,name=pinned_peer_public_key_sha256,json=pinnedPeerPublicKeySha256,proto3" json:"pinned_peer_public_key_sha256,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_masque_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_masque_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_masque_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Config) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Config) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *Config) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *Config) GetTransport() Config_Transport {
	if x != nil {
		return x.Transport
	}
	return Config_H3
}

func (x *Config) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *Config) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Config) GetConnectProtocol() string {
	if x != nil {
		return x.ConnectProtocol
	}
	return ""
}

func (x *Config) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *Config) GetDNS() []string {
	if x != nil {
		return x.DNS
	}
	return nil
}

func (x *Config) GetDomainStrategy() Config_DomainStrategy {
	if x != nil {
		return x.DomainStrategy
	}
	return Config_FORCE_IP
}

func (x *Config) GetPinnedPeerPublicKeySha256() []string {
	if x != nil {
		return x.PinnedPeerPublicKeySha256
	}
	return nil
}

var File_proxy_masque_config_proto protoreflect.FileDescriptor

const file_proxy_masque_config_proto_rawDesc = "" +
	"\n" +
	"\x19proxy/masque/config.proto\x12\x11xray.proxy.masque\"\xd5\x04\n" +
	"\x06Config\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x18\n" +
	"\aaddress\x18\x02 \x03(\tR\aaddress\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12 \n" +
	"\vcertificate\x18\x04 \x01(\tR\vcertificate\x12A\n" +
	"\ttransport\x18\x05 \x01(\x0e2#.xray.proxy.masque.Config.TransportR\ttransport\x12\x1c\n" +
	"\tauthority\x18\x06 \x01(\tR\tauthority\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12)\n" +
	"\x10connect_protocol\x18\b \x01(\tR\x0fconnectProtocol\x12\x10\n" +
	"\x03mtu\x18\t \x01(\x05R\x03mtu\x12\x10\n" +
	"\x03DNS\x18\n" +
	" \x03(\tR\x03DNS\x12Q\n" +
	"\x0fdomain_strategy\x18\v \x01(\x0e2(.xray.proxy.masque.Config.DomainStrategyR\x0edomainStrategy\x12@\n" +
	"\x1dpinned_peer_public_key_sha256\x18\f \x03(\tR\x19pinnedPeerPublicKeySha256\"\\\n" +
	"\x0eDomainStrategy\x12\f\n" +
	"\bFORCE_IP\x10\x00\x12\r\n" +
	"\tFORCE_IP4\x10\x01\x12\r\n" +
	"\tFORCE_IP6\x10\x02\x12\x0e\n" +
	"\n" +
	"FORCE_IP46\x10\x03\x12\x0e\n" +
	"\n" +
	"FORCE_IP64\x10\x04\"\x1b\n" +
	"\tTransport\x12\x06\n" +
	"\x02H3\x10\x00\x12\x06\n" +
	"\x02H2\x10\x01B\\\n" +
	"\x15com.xray.proxy.masqueP\x01Z-github.com/GFW-knocker/Xray-core/proxy/masque\xaa\x02\x11Xray.Proxy.Masqueb\x06proto3"

var (
	file_proxy_masque_config_proto_rawDescOnce sync.Once
	file_proxy_masque_config_proto_rawDescData []byte
)

func file_proxy_masque_config_proto_rawDescGZIP() []byte {
	file_proxy_masque_config_proto_rawDescOnce.Do(func() {
		file_proxy_masque_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_masque_config_proto_rawDesc), len(file_proxy_masque_config_proto_rawDesc)))
	})
	return file_proxy_masque_config_proto_rawDescData
}

var file_proxy_masque_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proxy_masque_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_masque_config_proto_goTypes = []any{
	(Config_DomainStrategy)(0), // 0: xray.proxy.masque.Config.DomainStrategy
	(Config_Transport)(0),      // 1: xray.proxy.masque.Config.Transport
	(*Config)(nil),             // 2: xray.proxy.masque.Config
}
var file_proxy_masque_config_proto_depIdxs = []int32{
	1, // 0: xray.proxy.masque.Config.transport:type_name -> xray.proxy.masque.Config.Transport
	0, // 1: xray.proxy.masque.Config.domain_strategy:type_name -> xray.proxy.masque.Config.DomainStrategy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_masque_config_proto_init() }
func file_proxy_masque_config_proto_init() {
	if File_proxy_masque_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_masque_config_proto_rawDesc), len(file_proxy_masque_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_masque_config_proto_goTypes,
		DependencyIndexes: file_proxy_masque_config_proto_depIdxs,
		EnumInfos:         file_proxy_masque_config_proto_enumTypes,
		MessageInfos:      file_proxy_masque_config_proto_msgTypes,
	}.Build()
	File_proxy_masque_config_proto = out.File
	file_proxy_masque_config_proto_goTypes = nil
	file_proxy_masque_config_proto_depIdxs = nil
}
