#!/usr/bin/env bash
#
# Prove that the committed MVLESS sources have not drifted from VLESS.
#
# Regenerates MVLESS from the current VLESS sources into a scratch directory
# and diffs the result against what is committed. Since sync-mvless.sh is a
# pure rename of VLESS plus a single version-byte patch, a clean diff here
# means MVLESS is VLESS with exactly one line changed.
#
#     bash infra/mvlessgen/verify-mvless.sh
#
# Exits non-zero on drift. Safe to run in CI.
#
# Note on why this does not simply un-rename MVLESS and diff the text: the
# rename changes identifier lengths, so a byte-exact source comparison is
# impossible even for a perfectly-synced tree. "mvless" is one byte longer than
# "vless", which shifts the length prefixes embedded in the protobuf rawDesc
# blobs, changes gofmt's struct-tag alignment, and re-sorts import blocks.
# Regenerating and comparing sidesteps all of it.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

MVLESS_VERSION_BYTE=150

scratch="$(mktemp -d)"
trap 'rm -rf "$scratch"' EXIT

bash "$ROOT/infra/mvlessgen/sync-mvless.sh" --out "$scratch" >"$scratch/.log" 2>&1 || {
	echo "verify-mvless: generation failed:" >&2
	cat "$scratch/.log" >&2
	exit 1
}
rm -f "$scratch/.log"

fail=0
while IFS= read -r rel; do
	if [ ! -f "$ROOT/$rel" ]; then
		echo "verify-mvless: missing from the working tree: $rel" >&2
		fail=1
		continue
	fi
	if ! cmp -s "$scratch/$rel" "$ROOT/$rel"; then
		echo "verify-mvless: out of sync: $rel" >&2
		# Compare with CR stripped so a content diff is readable; if that
		# comes back clean the files differ only in line endings.
		if diff -q <(tr -d '\r' <"$scratch/$rel") <(tr -d '\r' <"$ROOT/$rel") >/dev/null; then
			echo "  (line endings only)" >&2
		else
			diff -u <(tr -d '\r' <"$scratch/$rel") <(tr -d '\r' <"$ROOT/$rel") \
				| sed -n '3,40p' >&2 || true
		fi
		fail=1
	fi
done < <(cd "$scratch" && find . -type f | sed 's|^\./||')

# Files in proxy/mvless that the generator would not produce are drift too.
while IFS= read -r rel; do
	if [ ! -f "$scratch/$rel" ]; then
		echo "verify-mvless: not generated by sync-mvless.sh: $rel" >&2
		fail=1
	fi
done < <(cd "$ROOT" && find proxy/mvless -type f | sed 's|^\./||')

# Belt and braces: the version byte really is applied.
if ! grep -q "Version = byte(${MVLESS_VERSION_BYTE})" "$ROOT/proxy/mvless/encoding/encoding.go"; then
	echo "verify-mvless: proxy/mvless/encoding/encoding.go is not on version ${MVLESS_VERSION_BYTE}" >&2
	fail=1
fi

if [ "$fail" -ne 0 ]; then
	echo >&2
	echo "Run: bash infra/mvlessgen/sync-mvless.sh" >&2
	exit 1
fi

echo "verify-mvless: OK - MVLESS is in sync with VLESS (version byte ${MVLESS_VERSION_BYTE})."
