package tls

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/base64"
	"encoding/binary"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/GFW-knocker/Xray-core/common/crypto"
	utls "github.com/refraction-networking/utls"
	"golang.org/x/net/http2"

	"github.com/GFW-knocker/Xray-core/common/errors"
	"github.com/GFW-knocker/Xray-core/common/net"
	"github.com/GFW-knocker/Xray-core/common/utils"
	"github.com/GFW-knocker/Xray-core/transport/internet"
	"github.com/miekg/dns"
	"golang.org/x/crypto/cryptobyte"
)

// failClosedECHConfig is a deliberately malformed ECHConfigList. The TLS stack
// rejects it while parsing, so a handshake fails locally instead of silently
// falling back to a plaintext SNI when no real config could be obtained.
var failClosedECHConfig = []byte{1, 1, 4, 5, 1, 4}

func ApplyECH(c *Config, config *tls.Config) error {
	var ECHConfig []byte
	var err error

	var nameToQuery string
	if net.ParseAddress(config.ServerName).Family().IsDomain() {
		nameToQuery = config.ServerName
	}
	var DNSServer string

	// for server
	if len(c.EchServerKeys) != 0 {
		KeySets, err := ConvertToGoECHKeys(c.EchServerKeys)
		if err != nil {
			return errors.New("Failed to unmarshal ECHKeySetList: ", err)
		}
		config.EncryptedClientHelloKeys = KeySets
	}

	// for client
	if len(c.EchConfigList) != 0 {
		defer func() {
			// If no ECH config could be obtained, install a deliberately invalid one
			// so the handshake fails instead of silently falling back to a plaintext
			// SNI -- otherwise anyone able to block or strip the ECH DNS answer can
			// downgrade the connection on demand.
			//
			// len(ECHConfig) == 0 covers both a failed query and a query that
			// succeeded but carried no ECH record.
			if len(ECHConfig) == 0 {
				ECHConfig = failClosedECHConfig
			}
			config.EncryptedClientHelloConfigList = ECHConfig
		}()
		// learn the config from the server itself, no DNS involved
		if publicName, hostPort, isProbe := parseECHProbe(c.EchConfigList); isProbe {
			if !net.ParseAddress(publicName).Family().IsDomain() {
				return errors.New("ECH probe public name must be a domain, got: ", publicName)
			}
			rootCAs, poolErr := c.getCertPool()
			if poolErr != nil {
				errors.LogErrorInner(context.Background(), poolErr, "failed to load system root certificate for ECH probe")
			}
			fingerprint := GetFingerprint(c.Fingerprint)
			sockopt := c.EchSocketSettings
			server := echProbeScheme + "://" + hostPort
			rememberECHCacheKey(config, ECHCacheKey(server, publicName, sockopt))
			ECHConfig, err = queryECHConfig(server, publicName, sockopt,
				func() ([]byte, uint32, error) {
					return echProbe(context.Background(), hostPort, publicName, sockopt, fingerprint, rootCAs, c.AllowInsecure)
				})
			if err != nil {
				return errors.New("Failed to obtain ECH config by probing ", hostPort, " as ", publicName).Base(err)
			}
			return nil
		}
		// query config from dns
		if strings.Contains(c.EchConfigList, "://") {
			// parse ECH DNS server in format of "example.com+https://1.1.1.1/dns-query"
			parts := strings.SplitN(c.EchConfigList, "+", 2)
			if len(parts) == 2 {
				nameToQuery = parts[0]
				DNSServer = parts[1]
			} else {
				// normal format
				DNSServer = parts[0]
			}
			if nameToQuery == "" {
				return errors.New("Using DNS for ECH Config needs serverName or use Server format example.com+https://1.1.1.1/dns-query")
			}
			rememberECHCacheKey(config, ECHCacheKey(DNSServer, nameToQuery, c.EchSocketSettings))
			ECHConfig, err = QueryRecord(nameToQuery, DNSServer, c.EchSocketSettings)
			if err != nil {
				return errors.New("Failed to query ECH DNS record for domain: ", nameToQuery, " at server: ", DNSServer).Base(err)
			}
		} else {
			// direct base64 config
			ECHConfig, err = base64.StdEncoding.DecodeString(c.EchConfigList)
			if err != nil {
				return errors.New("Failed to unmarshal ECHConfigList: ", err)
			}
		}
	}

	return nil
}

type ECHConfigCache struct {
	configRecord atomic.Pointer[echConfigRecord]
	// updateLock is not for preventing concurrent read/write, but for preventing concurrent update
	UpdateLock sync.Mutex
}

type echConfigRecord struct {
	config []byte
	expire time.Time
	// err marks a negative record: the lookup failed and there was no usable
	// config to fall back on. Without one, every dial repeats the whole lookup
	// and pays its full timeout, and concurrent dials queue behind each other
	// on UpdateLock and then each repeat it again.
	err error
}

// echNegativeCacheTTL is how long a failed lookup is remembered. Long enough to
// stop a burst of dials from each paying the timeout, short enough that service
// coming back is noticed promptly.
const echNegativeCacheTTL = 30 * time.Second

var (
	// The keys for both maps must be generated by ECHCacheKey().
	GlobalECHConfigCache = utils.NewTypedSyncMap[string, *ECHConfigCache]()
	clientForECHDOH      = utils.NewTypedSyncMap[string, *http.Client]()
)

// sockopt can be nil if not specified.
// if for clientForECHDOH, domain can be empty.
func ECHCacheKey(server, domain string, sockopt *internet.SocketConfig) string {
	return server + "|" + domain + "|" + fmt.Sprintf("%p", sockopt)
}

// echFetcher obtains a fresh ECHConfigList along with the number of seconds it
// stays valid. dnsQuery and echProbe are the two implementations.
type echFetcher func() ([]byte, uint32, error)

// Update updates the ECH config for given domain and server.
// this method is concurrent safe, only one update request will be sent, others get the cache.
// if isLockedUpdate is true, it will not try to acquire the lock.
func (c *ECHConfigCache) Update(domain string, server string, isLockedUpdate bool, sockopt *internet.SocketConfig) ([]byte, error) {
	return c.UpdateWith(domain, server, isLockedUpdate, func() ([]byte, uint32, error) {
		return dnsQuery(server, domain, sockopt)
	})
}

// UpdateWith is Update with the acquisition method left to the caller.
func (c *ECHConfigCache) UpdateWith(domain string, server string, isLockedUpdate bool, fetch echFetcher) ([]byte, error) {
	if !isLockedUpdate {
		c.UpdateLock.Lock()
		defer c.UpdateLock.Unlock()
	}
	// Double check cache after acquiring lock. This is what stops a burst of
	// dials from each repeating a lookup that already failed: whoever loses the
	// lock race finds the negative record the winner just stored.
	configRecord := c.configRecord.Load()
	if configRecord.expire.After(time.Now()) {
		errors.LogDebug(context.Background(), "Cache hit for domain after double check: ", domain)
		return configRecord.config, configRecord.err
	}
	// Fetch ECH config from the configured source
	errors.LogDebug(context.Background(), "Trying to query ECH config for domain: ", domain, " with ECH server: ", server)
	echConfig, ttl, err := fetch()
	if err != nil {
		// Only remember the failure when there is nothing usable to fall back
		// on. A background refresh that fails must leave an existing config in
		// place, which is what the caller is still serving.
		if len(configRecord.config) == 0 {
			c.configRecord.Store(&echConfigRecord{
				err:    err,
				expire: time.Now().Add(echNegativeCacheTTL),
			})
		}
		return nil, err
	}
	configRecord = &echConfigRecord{
		config: echConfig,
		expire: time.Now().Add(time.Duration(ttl) * time.Second),
	}
	c.configRecord.Store(configRecord)
	return configRecord.config, nil
}

// QueryRecord returns the ECH config for given domain.
// If the record is not in cache or expired, it will query the DNS server and update the cache.
func QueryRecord(domain string, server string, sockopt *internet.SocketConfig) ([]byte, error) {
	return queryECHConfig(server, domain, sockopt, func() ([]byte, uint32, error) {
		return dnsQuery(server, domain, sockopt)
	})
}

// queryECHConfig is QueryRecord with the acquisition method left to the caller.
// server only identifies the cache entry here, so the probe and DNS paths cannot
// collide even when they name the same domain.
func queryECHConfig(server string, domain string, sockopt *internet.SocketConfig, fetch echFetcher) ([]byte, error) {
	GlobalECHConfigCacheKey := ECHCacheKey(server, domain, sockopt)
	echConfigCache, ok := GlobalECHConfigCache.Load(GlobalECHConfigCacheKey)
	if !ok {
		echConfigCache = &ECHConfigCache{}
		echConfigCache.configRecord.Store(&echConfigRecord{})
		echConfigCache, _ = GlobalECHConfigCache.LoadOrStore(GlobalECHConfigCacheKey, echConfigCache)
	}
	configRecord := echConfigCache.configRecord.Load()
	if configRecord.expire.After(time.Now()) {
		errors.LogDebug(context.Background(), "Cache hit for domain: ", domain)
		// A live negative record fails fast instead of repeating the lookup.
		return configRecord.config, configRecord.err
	}

	// If expire is zero value, it means we are in initial state, wait for the query to finish
	// otherwise return old value immediately and update in a goroutine
	// but if the cache is too old, wait for update
	// An expired negative record has no config to serve, so it waits too.
	if configRecord.expire.IsZero() || configRecord.err != nil || configRecord.expire.Add(time.Hour*6).Before(time.Now()) {
		return echConfigCache.UpdateWith(domain, server, false, fetch)
	} else {
		// If someone already acquired the lock, it means it is updating, do not start another update goroutine
		if echConfigCache.UpdateLock.TryLock() {
			go func() {
				defer echConfigCache.UpdateLock.Unlock()
				echConfigCache.UpdateWith(domain, server, true, fetch)
			}()
		}
		return configRecord.config, nil
	}
}

// dnsQuery is the real func for sending type65 query for given domain to given DNS server.
// return ECH config, TTL and error
func dnsQuery(server string, domain string, sockopt *internet.SocketConfig) ([]byte, uint32, error) {
	m := new(dns.Msg)
	var dnsResolve []byte
	m.SetQuestion(dns.Fqdn(domain), dns.TypeHTTPS)
	// for DOH server
	if strings.HasPrefix(server, "https://") || strings.HasPrefix(server, "h2c://") {
		h2c := strings.HasPrefix(server, "h2c://")
		m.SetEdns0(4096, false) // 4096 is the buffer size, false means no DNSSEC
		padding := &dns.EDNS0_PADDING{Padding: make([]byte, int(crypto.RandBetween(100, 300)))}
		if opt := m.IsEdns0(); opt != nil {
			opt.Option = append(opt.Option, padding)
		}
		// always 0 in DOH
		m.Id = 0
		msg, err := m.Pack()
		if err != nil {
			return nil, 0, err
		}
		var client *http.Client
		serverKey := ECHCacheKey(server, "", sockopt)
		if client, _ = clientForECHDOH.Load(serverKey); client == nil {
			// All traffic sent by core should via xray's internet.DialSystem
			// This involves the behavior of some Android VPN GUI clients
			tr := &http2.Transport{
				IdleConnTimeout: net.ConnIdleTimeout,
				ReadIdleTimeout: net.ChromeH2KeepAlivePeriod,
				DialTLSContext: func(ctx context.Context, network, addr string, cfg *tls.Config) (net.Conn, error) {
					dest, err := net.ParseDestination(network + ":" + addr)
					if err != nil {
						return nil, err
					}
					var conn net.Conn

					conn, err = internet.DialSystem(ctx, dest, sockopt)
					if err != nil {
						return nil, err
					}

					if !h2c {
						u, err := url.Parse(server)
						if err != nil {
							return nil, err
						}
						conn = utls.UClient(conn, &utls.Config{ServerName: u.Hostname()}, utls.HelloChrome_Auto)
						if err := conn.(*utls.UConn).HandshakeContext(ctx); err != nil {
							return nil, err
						}
					}
					return conn, nil
				},
			}
			c := &http.Client{
				Timeout:   30 * time.Second,
				Transport: tr,
			}
			client, _ = clientForECHDOH.LoadOrStore(serverKey, c)
		}
		req, err := http.NewRequest("POST", server, bytes.NewReader(msg))
		if err != nil {
			return nil, 0, err
		}
		// h2c: in config is just for claim
		// change scheme to https and expect outbound to handle TLS (freedom + tlsSetting)
		req.URL.Scheme = "https"
		req.Header.Set("Accept", "application/dns-message")
		req.Header.Set("Content-Type", "application/dns-message")
		utils.TryDefaultHeadersWith(req.Header, "fetch")
		req.Header.Set("X-Padding", utils.H2Base62Pad(crypto.RandBetween(100, 1000)))

		resp, err := client.Do(req)
		if err != nil {
			return nil, 0, err
		}
		defer resp.Body.Close()
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, 0, err
		}
		if resp.StatusCode != http.StatusOK {
			return nil, 0, errors.New("query failed with response code:", resp.StatusCode)
		}
		dnsResolve = respBody
	} else if strings.HasPrefix(server, "udp://") { // for classic udp dns server
		udpServerURL, err := url.Parse(server)
		if err != nil {
			return nil, 0, errors.New("failed to parse udp dns server ", server, " for ECH: ", err)
		}
		// default port 53 if not specified
		if udpServerURL.Port() == "" {
			udpServerURL.Host = udpServerURL.Host + ":53"
		}
		dest, err := net.ParseDestination("udp" + ":" + udpServerURL.Host)
		if err != nil {
			return nil, 0, errors.New("failed to parse udp dns server ", udpServerURL.Host, " for ECH: ", err)
		}
		dnsTimeoutCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		// use xray's internet.DialSystem as mentioned above
		conn, err := internet.DialSystem(dnsTimeoutCtx, dest, sockopt)
		if err != nil {
			return nil, 0, err
		}
		defer func() {
			err := conn.Close()
			if err != nil {
				errors.LogDebug(context.Background(), "Failed to close connection: ", err)
			}
		}()
		msg, err := m.Pack()
		if err != nil {
			return nil, 0, err
		}
		conn.Write(msg)
		udpResponse := make([]byte, 512)
		conn.SetReadDeadline(time.Now().Add(5 * time.Second))
		_, err = conn.Read(udpResponse)
		if err != nil {
			return nil, 0, err
		}
		dnsResolve = udpResponse
	}
	respMsg := new(dns.Msg)
	err := respMsg.Unpack(dnsResolve)
	if err != nil {
		return nil, 0, errors.New("failed to unpack dns response for ECH: ", err)
	}
	// Reject an answer that does not echo the transaction ID we sent. RFC 1035
	// requires the echo, so this breaks nothing, and it costs a blind spoofer
	// the chance to win the race with a guessed packet. It is no defence at all
	// against an on-path attacker, who simply reads the ID -- plaintext DNS
	// cannot be made safe here, which is what warnIfPlaintextECHDNS says.
	// DoH pins the ID to 0 (RFC 8484) and is authenticated by TLS regardless.
	if m.Id != 0 && respMsg.Id != m.Id {
		return nil, 0, errors.New("dns response for ECH has mismatched transaction ID")
	}
	if len(respMsg.Answer) > 0 {
		for _, answer := range respMsg.Answer {
			if https, ok := answer.(*dns.HTTPS); ok && https.Hdr.Name == dns.Fqdn(domain) {
				for _, v := range https.Value {
					if echConfig, ok := v.(*dns.SVCBECHConfig); ok {
						errors.LogDebug(context.Background(), "Get ECH config:", echConfig.String(), " TTL:", respMsg.Answer[0].Header().Ttl)
						return echConfig.ECH, answer.Header().Ttl, nil
					}
				}
			}
		}
	}
	return nil, 0, errors.New("no valid ECH config found in DNS response")
}

var ErrInvalidLen = errors.New("goech: invalid length")

func ConvertToGoECHKeys(data []byte) ([]tls.EncryptedClientHelloKey, error) {
	var keys []tls.EncryptedClientHelloKey
	s := cryptobyte.String(data)
	for !s.Empty() {
		if len(s) < 2 {
			return keys, ErrInvalidLen
		}
		keyLength := int(binary.BigEndian.Uint16(s[:2]))
		if len(s) < keyLength+4 {
			return keys, ErrInvalidLen
		}
		configLength := int(binary.BigEndian.Uint16(s[keyLength+2 : keyLength+4]))
		if len(s) < 2+keyLength+2+configLength {
			return keys, ErrInvalidLen
		}
		child := cryptobyte.String(s[:2+keyLength+2+configLength])
		var sk, config cryptobyte.String
		if !child.ReadUint16LengthPrefixed(&sk) || !child.ReadUint16LengthPrefixed(&config) || !child.Empty() {
			return keys, ErrInvalidLen
		}
		if !s.Skip(2 + keyLength + 2 + configLength) {
			return keys, ErrInvalidLen
		}
		keys = append(keys, tls.EncryptedClientHelloKey{
			Config:     config,
			PrivateKey: sk,
			// Answer a client whose config is stale with the current one, the
			// way Cloudflare does. Without this the server refuses the ECH but
			// never says what would work, so a key rotation breaks every client
			// until each config is updated by hand. The value handed out is the
			// public half, the same bytes that go in a DNS record.
			SendAsRetry: true,
		})
	}
	return keys, nil
}
